In [16]:
!pip install numpy
#shift enter to run


[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
#convention to load numpy as np
import numpy as np

In [6]:
data= np.random.rand(2,3,4)
zeroes = np.zeros((2,2,2))
full= np.full((2,2,2),7)
ones= np.ones((2,2,2))

In [8]:
#in the next code we will see the outputs
data



array([[[4.00371572e-01, 8.79758120e-01, 9.51191465e-01, 5.23867078e-01],
        [5.84801792e-01, 1.92464980e-01, 9.07714656e-04, 7.03503400e-01],
        [2.40381945e-01, 1.18366673e-02, 3.96975577e-01, 5.16347045e-01]],

       [[3.73208737e-01, 3.71958906e-01, 3.69164483e-02, 3.69395873e-01],
        [4.59991534e-01, 3.94848048e-01, 3.83817637e-01, 3.25596967e-01],
        [7.09411878e-01, 5.88001482e-01, 3.23727845e-01, 2.05976002e-01]]])

In [9]:
zeroes

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [10]:
full

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [11]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [14]:
#here creating an array with pre given data
arr = np.array([[1,2,3,4],[1,2,3,4]])


In [13]:
arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [15]:
type(arr)

numpy.ndarray