In [17]:
!pip install numpy
#shift enter to run and proceed


[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
#convention to load numpy as np
import numpy as np

In [6]:
data= np.random.rand(2,3,4)
zeroes = np.zeros((2,2,2))
full= np.full((2,2,2),7)
ones= np.ones((2,2,2))

In [18]:
#in the next code we will see the outputs
data



array([[[4.00371572e-01, 8.79758120e-01, 9.51191465e-01, 5.23867078e-01],
        [5.84801792e-01, 1.92464980e-01, 9.07714656e-04, 7.03503400e-01],
        [2.40381945e-01, 1.18366673e-02, 3.96975577e-01, 5.16347045e-01]],

       [[3.73208737e-01, 3.71958906e-01, 3.69164483e-02, 3.69395873e-01],
        [4.59991534e-01, 3.94848048e-01, 3.83817637e-01, 3.25596967e-01],
        [7.09411878e-01, 5.88001482e-01, 3.23727845e-01, 2.05976002e-01]]])

In [22]:
#here generating a numpy array with pre given data
arr = np.array([[1,2,3,4],[1,2,3,4]])


In [13]:
arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [21]:
type(arr)#typecheck

numpy.ndarray

In [25]:
#attributes
shape= data.shape
size= data.size
types=data.dtype


In [28]:
shape



(2, 3, 4)

In [29]:
size

24

In [30]:
types

dtype('float64')

In [43]:
list1= np.random.rand(10)
list2= np.random.rand(10)
list2

array([0.1740148 , 0.11204764, 0.22127738, 0.79056038, 0.22007161,
       0.57690415, 0.04913741, 0.60368657, 0.45718741, 0.42467097])

In [46]:
#basic math they are superfast
add = np.add(list1,list2)
sub= np.subtract(list1, list2)
div= np.divide(list1,list2)
mult= np.multiply(list1,list2)
dot = np.dot(list1, list2)

In [47]:
add


array([1.05332122, 0.95248733, 0.56835143, 1.67537065, 0.37831129,
       1.33612721, 0.52097987, 1.21976513, 1.20924379, 0.58504356])

In [49]:
#statistical functions
sqrt = np.sqrt(25)
ab = np.abs(-2)
power= np.power(2,7)
log = np.log(25)
exp = np.exp([2,3])
mins= np.min(list1)
maxs= np.max(list1)
             

In [50]:
#updating
data[0][0][0]=100


In [51]:
data

array([[[1.00000000e+02, 8.79758120e-01, 9.51191465e-01, 5.23867078e-01],
        [5.84801792e-01, 1.92464980e-01, 9.07714656e-04, 7.03503400e-01],
        [2.40381945e-01, 1.18366673e-02, 3.96975577e-01, 5.16347045e-01]],

       [[3.73208737e-01, 3.71958906e-01, 3.69164483e-02, 3.69395873e-01],
        [4.59991534e-01, 3.94848048e-01, 3.83817637e-01, 3.25596967e-01],
        [7.09411878e-01, 5.88001482e-01, 3.23727845e-01, 2.05976002e-01]]])

In [52]:
data.sort() #sort data

In [53]:
data


array([[[5.23867078e-01, 8.79758120e-01, 9.51191465e-01, 1.00000000e+02],
        [9.07714656e-04, 1.92464980e-01, 5.84801792e-01, 7.03503400e-01],
        [1.18366673e-02, 2.40381945e-01, 3.96975577e-01, 5.16347045e-01]],

       [[3.69164483e-02, 3.69395873e-01, 3.71958906e-01, 3.73208737e-01],
        [3.25596967e-01, 3.83817637e-01, 3.94848048e-01, 4.59991534e-01],
        [2.05976002e-01, 3.23727845e-01, 5.88001482e-01, 7.09411878e-01]]])

In [54]:
print(data.shape)


(2, 3, 4)


In [55]:
data= data.reshape((2,2,-1))
data.shape # here shaping it in 2 2 and the last part can be anything

(2, 2, 6)

In [60]:
zeroes = np.zeros((8))
print(zeroes)
zeroes = np.append(zeroes,[3,4])#here appending the [3,4] arrays
print(zeroes)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]


In [61]:
#insert in specific area
zeroes = np.insert(zeroes,2,1)#insert the value 1 at position 2
zeroes


array([0., 0., 1., 0., 0., 0., 0., 0., 0., 3., 4.])

In [85]:
zeroes= np.zeros((4,3))
print(zeroes)
zeroes


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [86]:
zeroes= np.insert(zeroes,1,[1,2,3,4],1)
zeroes

array([[0., 1., 0., 0.],
       [0., 2., 0., 0.],
       [0., 3., 0., 0.],
       [0., 4., 0., 0.]])