In [17]:
!pip install numpy
#shift enter to run and proceed


[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
#convention to load numpy as np
import numpy as np

In [6]:
data= np.random.rand(2,3,4)
zeroes = np.zeros((2,2,2))
full= np.full((2,2,2),7)
ones= np.ones((2,2,2))

In [18]:
#in the next code we will see the outputs
data



array([[[4.00371572e-01, 8.79758120e-01, 9.51191465e-01, 5.23867078e-01],
        [5.84801792e-01, 1.92464980e-01, 9.07714656e-04, 7.03503400e-01],
        [2.40381945e-01, 1.18366673e-02, 3.96975577e-01, 5.16347045e-01]],

       [[3.73208737e-01, 3.71958906e-01, 3.69164483e-02, 3.69395873e-01],
        [4.59991534e-01, 3.94848048e-01, 3.83817637e-01, 3.25596967e-01],
        [7.09411878e-01, 5.88001482e-01, 3.23727845e-01, 2.05976002e-01]]])

In [22]:
#here generating a numpy array with pre given data
arr = np.array([[1,2,3,4],[1,2,3,4]])


In [13]:
arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [21]:
type(arr)#typecheck

numpy.ndarray

In [25]:
#attributes
shape= data.shape
size= data.size
types=data.dtype


In [28]:
shape



(2, 3, 4)

In [29]:
size

24

In [30]:
types

dtype('float64')

In [36]:
#slicing
arr= data[0]
slicer= data[0][0:2]
reverse= data[-1]
singleval=data[0][0][0]

In [37]:
arr#grab first instance here data is 2,3,4 is it will give the first indexes 3,4 array

array([[4.00371572e-01, 8.79758120e-01, 9.51191465e-01, 5.23867078e-01],
       [5.84801792e-01, 1.92464980e-01, 9.07714656e-04, 7.03503400e-01],
       [2.40381945e-01, 1.18366673e-02, 3.96975577e-01, 5.16347045e-01]])

In [39]:
slicer#  here [0:2] means the of 2,3,4's first two 3,4 and [0][0:2] means in 3,4 the first two of 4's array so it will return two 4 sized array

array([[4.00371572e-01, 8.79758120e-01, 9.51191465e-01, 5.23867078e-01],
       [5.84801792e-01, 1.92464980e-01, 9.07714656e-04, 7.03503400e-01]])

In [42]:
reverse#will index from reverse and rest is same

array([[0.37320874, 0.37195891, 0.03691645, 0.36939587],
       [0.45999153, 0.39484805, 0.38381764, 0.32559697],
       [0.70941188, 0.58800148, 0.32372784, 0.205976  ]])

array([[[4.00371572e-01, 8.79758120e-01, 9.51191465e-01, 5.23867078e-01],
        [5.84801792e-01, 1.92464980e-01, 9.07714656e-04, 7.03503400e-01],
        [2.40381945e-01, 1.18366673e-02, 3.96975577e-01, 5.16347045e-01]],

       [[3.73208737e-01, 3.71958906e-01, 3.69164483e-02, 3.69395873e-01],
        [4.59991534e-01, 3.94848048e-01, 3.83817637e-01, 3.25596967e-01],
        [7.09411878e-01, 5.88001482e-01, 3.23727845e-01, 2.05976002e-01]]])